### ISSUE TITLE
Example with gzip?

### ISSUE THREAD

**Issue by rustrust** [althonos/uniprot.rs#12]
Would you mind writing a working example using a gzip with this (especially using libflate)?

I have tried using both libflate and flate2 to parse uniref90.xml.gz without ungzipping it. Although my code compiles and runs, it appears to never parse anything. I am wrapping the flate2::read::GzDecoder or libflate::gzip::Decoder in a BufReader and I've tried being explicit about creating a SequentialParser. 

```
    let input_file = File::open(input_filename).expect(&format!("Can't open file: {}", input_filename));
    let input_reader = BufReader::new(input_file);

    let gzdecoder = GzDecoder::new(input_reader);
    let brg = BufReader::new(gzdecoder);

    for r in uniprot::parser::SequentialParser::new(brg) {
       println!("works");  // this never prints
       let entry = r.unwrap();
   }
```

**Comment by althonos** [comment]
Hi @rustrust ,

in itself, your example is correct, but this library is not capable of processing UniRef files, only UniProtKB (strictly speaking: https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz for SwissProt, and https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.xml.gz for TrEMBL).

I may get around writing another crate for UniRef files, in which case I'll try to remember to ping you. Cheers!

**Comment by althonos** [comment]
I have added support for UniRef and UniProt in `v0.4.0`. This will now work:
```rust
    let input_file = File::open(input_filename).expect(&format!("Can't open file: {}", input_filename));
    let input_reader = BufReader::new(input_file);

    let gzdecoder = GzDecoder::new(input_reader);
    let brg = BufReader::new(gzdecoder);

    for r in uniprot::uniref::parse(brg) {
       println!("works");  // this never prints
       let entry = r.unwrap();
   }
```

Furthermore, I added a check when entering the XML dom to make sure the root element has the expected name (`UniRefXX` for UniRef, `uniprot` for UniProt, `uniparc` for UniParc), so in the case you use the wrong function (e.g., parsing UniProt with `uniprot::uniref::parse`) you'll now get an error instead of just failing silently / entering an endless loop.
